spring:
  application:
    name: bonsaibackend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bonsai
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
management:
  port: 9002
  address: 127.0.0.1
server:
  port: 8080

bonsai:
  graphstore: graph.store

logging:
  level:
    org:
      springframework:
        web: DEBUG
